id: P006645
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-17 12:12:35.069464
source_metadata:
  id: bdr:W1KG4479
  title: བསྟན་སྙིང་ཡིག་ཆ།
  author: ''
  volumes:
    2a22f33008644771ae070a64d5831650:
      image_group_id: I1KG4515
      title: ''
      volume_number: 1
      total_pages: 836
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
